// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: dodgeball.proto

package dodgeballpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DodgeballService_RunSimulation_FullMethodName = "/dodgeball.DodgeballService/RunSimulation"
)

// DodgeballServiceClient is the client API for DodgeballService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DodgeballServiceClient interface {
	RunSimulation(ctx context.Context, in *SimulationInput, opts ...grpc.CallOption) (*SimulationResult, error)
}

type dodgeballServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDodgeballServiceClient(cc grpc.ClientConnInterface) DodgeballServiceClient {
	return &dodgeballServiceClient{cc}
}

func (c *dodgeballServiceClient) RunSimulation(ctx context.Context, in *SimulationInput, opts ...grpc.CallOption) (*SimulationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationResult)
	err := c.cc.Invoke(ctx, DodgeballService_RunSimulation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DodgeballServiceServer is the server API for DodgeballService service.
// All implementations must embed UnimplementedDodgeballServiceServer
// for forward compatibility.
type DodgeballServiceServer interface {
	RunSimulation(context.Context, *SimulationInput) (*SimulationResult, error)
	mustEmbedUnimplementedDodgeballServiceServer()
}

// UnimplementedDodgeballServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDodgeballServiceServer struct{}

func (UnimplementedDodgeballServiceServer) RunSimulation(context.Context, *SimulationInput) (*SimulationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSimulation not implemented")
}
func (UnimplementedDodgeballServiceServer) mustEmbedUnimplementedDodgeballServiceServer() {}
func (UnimplementedDodgeballServiceServer) testEmbeddedByValue()                          {}

// UnsafeDodgeballServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DodgeballServiceServer will
// result in compilation errors.
type UnsafeDodgeballServiceServer interface {
	mustEmbedUnimplementedDodgeballServiceServer()
}

func RegisterDodgeballServiceServer(s grpc.ServiceRegistrar, srv DodgeballServiceServer) {
	// If the following call pancis, it indicates UnimplementedDodgeballServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DodgeballService_ServiceDesc, srv)
}

func _DodgeballService_RunSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DodgeballServiceServer).RunSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DodgeballService_RunSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DodgeballServiceServer).RunSimulation(ctx, req.(*SimulationInput))
	}
	return interceptor(ctx, in, info, handler)
}

// DodgeballService_ServiceDesc is the grpc.ServiceDesc for DodgeballService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DodgeballService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dodgeball.DodgeballService",
	HandlerType: (*DodgeballServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunSimulation",
			Handler:    _DodgeballService_RunSimulation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dodgeball.proto",
}
