// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: dodgeball.proto

package dodgeballpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int64                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int64                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Alive         bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_dodgeball_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_dodgeball_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_dodgeball_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Player) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Player) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type SimulationInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Players        []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	StartDirection int32                  `protobuf:"varint,2,opt,name=start_direction,json=startDirection,proto3" json:"start_direction,omitempty"`
	StartIndex     int32                  `protobuf:"varint,3,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SimulationInput) Reset() {
	*x = SimulationInput{}
	mi := &file_dodgeball_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationInput) ProtoMessage() {}

func (x *SimulationInput) ProtoReflect() protoreflect.Message {
	mi := &file_dodgeball_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationInput.ProtoReflect.Descriptor instead.
func (*SimulationInput) Descriptor() ([]byte, []int) {
	return file_dodgeball_proto_rawDescGZIP(), []int{1}
}

func (x *SimulationInput) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *SimulationInput) GetStartDirection() int32 {
	if x != nil {
		return x.StartDirection
	}
	return 0
}

func (x *SimulationInput) GetStartIndex() int32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

type SimulationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Throws        int32                  `protobuf:"varint,1,opt,name=throws,proto3" json:"throws,omitempty"`
	LastPlayer    int32                  `protobuf:"varint,2,opt,name=last_player,json=lastPlayer,proto3" json:"last_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationResult) Reset() {
	*x = SimulationResult{}
	mi := &file_dodgeball_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationResult) ProtoMessage() {}

func (x *SimulationResult) ProtoReflect() protoreflect.Message {
	mi := &file_dodgeball_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationResult.ProtoReflect.Descriptor instead.
func (*SimulationResult) Descriptor() ([]byte, []int) {
	return file_dodgeball_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationResult) GetThrows() int32 {
	if x != nil {
		return x.Throws
	}
	return 0
}

func (x *SimulationResult) GetLastPlayer() int32 {
	if x != nil {
		return x.LastPlayer
	}
	return 0
}

var File_dodgeball_proto protoreflect.FileDescriptor

const file_dodgeball_proto_rawDesc = "" +
	"\n" +
	"\x0fdodgeball.proto\x12\tdodgeball\":\n" +
	"\x06Player\x12\f\n" +
	"\x01x\x18\x01 \x01(\x03R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x03R\x01y\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\"\x88\x01\n" +
	"\x0fSimulationInput\x12+\n" +
	"\aplayers\x18\x01 \x03(\v2\x11.dodgeball.PlayerR\aplayers\x12'\n" +
	"\x0fstart_direction\x18\x02 \x01(\x05R\x0estartDirection\x12\x1f\n" +
	"\vstart_index\x18\x03 \x01(\x05R\n" +
	"startIndex\"K\n" +
	"\x10SimulationResult\x12\x16\n" +
	"\x06throws\x18\x01 \x01(\x05R\x06throws\x12\x1f\n" +
	"\vlast_player\x18\x02 \x01(\x05R\n" +
	"lastPlayer2\\\n" +
	"\x10DodgeballService\x12H\n" +
	"\rRunSimulation\x12\x1a.dodgeball.SimulationInput\x1a\x1b.dodgeball.SimulationResultB$Z\"dodgeball-go/proto_gen;dodgeballpbb\x06proto3"

var (
	file_dodgeball_proto_rawDescOnce sync.Once
	file_dodgeball_proto_rawDescData []byte
)

func file_dodgeball_proto_rawDescGZIP() []byte {
	file_dodgeball_proto_rawDescOnce.Do(func() {
		file_dodgeball_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dodgeball_proto_rawDesc), len(file_dodgeball_proto_rawDesc)))
	})
	return file_dodgeball_proto_rawDescData
}

var file_dodgeball_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dodgeball_proto_goTypes = []any{
	(*Player)(nil),           // 0: dodgeball.Player
	(*SimulationInput)(nil),  // 1: dodgeball.SimulationInput
	(*SimulationResult)(nil), // 2: dodgeball.SimulationResult
}
var file_dodgeball_proto_depIdxs = []int32{
	0, // 0: dodgeball.SimulationInput.players:type_name -> dodgeball.Player
	1, // 1: dodgeball.DodgeballService.RunSimulation:input_type -> dodgeball.SimulationInput
	2, // 2: dodgeball.DodgeballService.RunSimulation:output_type -> dodgeball.SimulationResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dodgeball_proto_init() }
func file_dodgeball_proto_init() {
	if File_dodgeball_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dodgeball_proto_rawDesc), len(file_dodgeball_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dodgeball_proto_goTypes,
		DependencyIndexes: file_dodgeball_proto_depIdxs,
		MessageInfos:      file_dodgeball_proto_msgTypes,
	}.Build()
	File_dodgeball_proto = out.File
	file_dodgeball_proto_goTypes = nil
	file_dodgeball_proto_depIdxs = nil
}
