// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: dodgeball.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "dodgeball";

export interface Player {
  x: number;
  y: number;
  alive: boolean;
}

export interface SimulationInput {
  players: Player[];
  startDirection: number;
  startIndex: number;
}

export interface SimulationResult {
  throws: number;
  lastPlayer: number;
}

function createBasePlayer(): Player {
  return { x: 0, y: 0, alive: false };
}

export const Player: MessageFns<Player> = {
  encode(message: Player, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.x !== 0) {
      writer.uint32(8).int64(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(16).int64(message.y);
    }
    if (message.alive !== false) {
      writer.uint32(24).bool(message.alive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Player {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.x = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.y = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.alive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Player {
    return {
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      alive: isSet(object.alive) ? globalThis.Boolean(object.alive) : false,
    };
  },

  toJSON(message: Player): unknown {
    const obj: any = {};
    if (message.x !== 0) {
      obj.x = Math.round(message.x);
    }
    if (message.y !== 0) {
      obj.y = Math.round(message.y);
    }
    if (message.alive !== false) {
      obj.alive = message.alive;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Player>, I>>(base?: I): Player {
    return Player.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Player>, I>>(object: I): Player {
    const message = createBasePlayer();
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.alive = object.alive ?? false;
    return message;
  },
};

function createBaseSimulationInput(): SimulationInput {
  return { players: [], startDirection: 0, startIndex: 0 };
}

export const SimulationInput: MessageFns<SimulationInput> = {
  encode(message: SimulationInput, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.players) {
      Player.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.startDirection !== 0) {
      writer.uint32(16).int32(message.startDirection);
    }
    if (message.startIndex !== 0) {
      writer.uint32(24).int32(message.startIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimulationInput {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimulationInput();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.players.push(Player.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.startDirection = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.startIndex = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SimulationInput {
    return {
      players: globalThis.Array.isArray(object?.players) ? object.players.map((e: any) => Player.fromJSON(e)) : [],
      startDirection: isSet(object.startDirection) ? globalThis.Number(object.startDirection) : 0,
      startIndex: isSet(object.startIndex) ? globalThis.Number(object.startIndex) : 0,
    };
  },

  toJSON(message: SimulationInput): unknown {
    const obj: any = {};
    if (message.players?.length) {
      obj.players = message.players.map((e) => Player.toJSON(e));
    }
    if (message.startDirection !== 0) {
      obj.startDirection = Math.round(message.startDirection);
    }
    if (message.startIndex !== 0) {
      obj.startIndex = Math.round(message.startIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimulationInput>, I>>(base?: I): SimulationInput {
    return SimulationInput.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimulationInput>, I>>(object: I): SimulationInput {
    const message = createBaseSimulationInput();
    message.players = object.players?.map((e) => Player.fromPartial(e)) || [];
    message.startDirection = object.startDirection ?? 0;
    message.startIndex = object.startIndex ?? 0;
    return message;
  },
};

function createBaseSimulationResult(): SimulationResult {
  return { throws: 0, lastPlayer: 0 };
}

export const SimulationResult: MessageFns<SimulationResult> = {
  encode(message: SimulationResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.throws !== 0) {
      writer.uint32(8).int32(message.throws);
    }
    if (message.lastPlayer !== 0) {
      writer.uint32(16).int32(message.lastPlayer);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimulationResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimulationResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.throws = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lastPlayer = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SimulationResult {
    return {
      throws: isSet(object.throws) ? globalThis.Number(object.throws) : 0,
      lastPlayer: isSet(object.lastPlayer) ? globalThis.Number(object.lastPlayer) : 0,
    };
  },

  toJSON(message: SimulationResult): unknown {
    const obj: any = {};
    if (message.throws !== 0) {
      obj.throws = Math.round(message.throws);
    }
    if (message.lastPlayer !== 0) {
      obj.lastPlayer = Math.round(message.lastPlayer);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SimulationResult>, I>>(base?: I): SimulationResult {
    return SimulationResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimulationResult>, I>>(object: I): SimulationResult {
    const message = createBaseSimulationResult();
    message.throws = object.throws ?? 0;
    message.lastPlayer = object.lastPlayer ?? 0;
    return message;
  },
};

export interface DodgeballService {
  RunSimulation(request: SimulationInput): Promise<SimulationResult>;
}

export const DodgeballServiceServiceName = "dodgeball.DodgeballService";
export class DodgeballServiceClientImpl implements DodgeballService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || DodgeballServiceServiceName;
    this.rpc = rpc;
    this.RunSimulation = this.RunSimulation.bind(this);
  }
  RunSimulation(request: SimulationInput): Promise<SimulationResult> {
    const data = SimulationInput.encode(request).finish();
    const promise = this.rpc.request(this.service, "RunSimulation", data);
    return promise.then((data) => SimulationResult.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
